### ISSUE TITLE
v2.2.2 small issue

### ISSUE THREAD

**Issue by simogeo** [servocoder/RichFilemanager#120] opened 2017-03-03 12:34 UTC
the index page is both : 

- calling <script type="text/javascript" src="config/filemanager.init.js"></script>
- creating an instance of richFileManager

Why don't you just provide `config/filemanager.init.js` instead of `config/filemanager.init.js.example`

**Comment by servocoder** [comment] 2017-03-03 20:05
Hi Simon!

The reason is the same as for `filemanager.config.default.json`
This file was created to implement callback functions which are configurable by user, because it's not possible to define functions in the json file. Since user can modify the file I don't want to have it under Git control. There is a similar concern about `config.php` file in #90, perhaps it makes sense to do the same with this file too.

**Comment by servocoder** [comment] 2017-03-03 20:08
Btw, I can see that you use v2.2.2
Can you reproduce / confirm the problem described in the #119 ?

**Comment by simogeo** [comment] 2017-03-04 10:10
> Since user can modify the file I don't want to have it under Git control. 

Understand. But I guess most of users will just implement the RFM out of the box calling an inexisting file.

I just test now your RFM implementation on my own server. It works well. But I have few observations : 
- I don't really get how the _cut / paste / clear clipboard_ tools works ....
- when clicking a folder in left panel, the right panel is not refreshing. Is that a wanted behavior ? Example :  My_folder1 > My_folder2. I guess it should list all files, no ?
- is there an optional way to remove + and - icons on older when opened / closed ? From an aesthetic point of view, I prefered the way it is handle by FM (http://fm.linea21.com/)
- bug : when copying PDF / ODT file URL I get this link : ./scripts/ViewerJS/index.html#http://fm.devale.pro/userfiles/My_folder1/virtual_layer_cle01d9cb.pdf?time=1488621919394. 
- bug : when copying .txt file URL, it seems it does not work ....

**Comment by servocoder** [comment] 2017-03-04 14:40
> But I guess most of users will just implement the RFM out of the box calling an inexisting file.

You are right, but I don't have a quick solution for this in case. Do you suggest to remove ".example" postfix and include this file to the Git?

1. Clipboard tool works in the same way as in the most of file browsers: select files on grid/list view and cut/copy. Then open desired folder and paste. However clipboard tool doesn't cover the preview mode. Have your asked about it for the preview page? Guess so )

2. I can reproduce this when I have file opened in the preview mode. Is that what you mean? This is not expected behavior, definetely.

3. I have to check it. I believe it's not a complex thing, even if it is not implemented yet. However note that in v2.2.2 an expanded folder isn't collapsed when you click on its name/icon, this action just refreshes files list. The only way to collapse folder in the filetree is to click on the "-" icon. It is act in the same way as in the Windows' Exporer file manager.

4-5. Bugs confirmed. Thanks for the reporting.

**Comment by simogeo** [comment] 2017-03-04 18:05
> However clipboard tool doesn't cover the preview mode. Have your asked about it for the preview page? Guess so )

ok, that's why I got lost. Thanks

> I can reproduce this when I have file opened in the preview mode. Is that what you mean? This is not expected behavior, definetely.

In preview mode, yes. This also happens with image

> I have to check it. I believe it's not a complex thing, even if it is not implemented yet. However note that in v2.2.2 an expanded folder isn't collapsed when you click on its name/icon, this action just refreshes files list. The only way to collapse folder in the filetree is to click on the "-" icon. It is act in the same way as in the Windows' Exporer file manager.

hummm .... ok

Ok for bugs

**Comment by servocoder** [comment] 2017-03-17 18:17
Fixed in v2.3.0

**Closed by servocoder** 2017-03-17 18:17 UTC
Labels: bug
