### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by billzt** [servocoder/RichFilemanager#56] opened 2016-10-25 09:31 UTC
I have a file of ~500MB already on my server. When I try to download it through RichFilemanager, it calls:

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 575025152 bytes) in /var/www/html/RichFilemanager/connectors/php/LocalFilemanager.php on line 683
```

Well, my memory_limit of php is 128MB. Should I just need to increase it?

**Comment by simogeo** [comment] 2016-10-25 09:37
FYI, see https://github.com/simogeo/Filemanager/issues/510

**Comment by servocoder** [comment] 2016-10-25 12:03
Are you sure you are trying to download file, not folder?
Cause I have got similar error while downloading folder with big media file. RFM try to zip it and fails with memory size error. But I'm unable to catch it when I try to download the media file directly.

Btw what vervion of RFM you use? master or dev branch?

**Comment by servocoder** [comment] 2016-10-25 14:35
I have fixed the error that happened upon folder downloading (my case) at the DEV branch. Your case still require details and investigation.

**Comment by billzt** [comment] 2016-10-26 00:03
@servocoder I'am trying to download a zip file, which contains several files in it. I don't know how many files in it

**Comment by servocoder** [comment] 2016-10-26 06:10
Files downloading process shouldn't cause such type of error.
You haven't answered about the version of RichFilenamager you use and the branch where you get it (dev or master). Information about your platform (Linux/Windows) can be helpful as well. Also share the code snippet you have at `/var/www/html/RichFilemanager/connectors/php/LocalFilemanager.php on line 683`, and lines beside line 683, please.

**Comment by billzt** [comment] 2016-10-26 09:33
Well, current my version is the previous master branch, commit 245d50ce02c6380a6ccb4f80996ddc1c1f9e67f8 

My platform is Linux, CentOS 6.8, PHP 5.6.6

LocalFilemanager.php on line 683:
```php
		header('Content-Description: File Transfer');
		header('Content-Type: ' . mime_content_type($current_path));
		header('Content-Disposition: attachment; filename=' . $filename);
		header('Content-Transfer-Encoding: binary');
		header('Content-Length: ' . $this->get_real_filesize($current_path));
		// handle caching
		header('Pragma: public');
		header('Expires: 0');
		header('Cache-Control: must-revalidate, post-check=0, pre-check=0');

(Line	683)	readfile($current_path);
		$this->__log('file downloaded "' . $current_path . '"');
		exit();
	}
```

**Comment by servocoder** [comment] 2016-10-26 10:10
Thanks for the details. I will try to reproduce it.

BTW you could also do some stuff to help. If possible, test your issue at the [DEV branch](https://github.com/servocoder/RichFilemanager/tree/dev). So we can ensure that the problem exists (or solved) at the latest version.

**Comment by servocoder** [comment] 2016-10-30 20:54
Check out the latest commit on DEV branch. The problem should be fixed.

**Comment by billzt** [comment] 2016-10-31 02:56
Well, I check the commit de5bbf7c3d44f66dc4f2c0436fee4dee49b2f7e5 and manually merge it to release versions (such as 1.0.5) and it is OK. The DEV branch fails to set up the main working instances, perhaps there exists too many commits and includes additional bugs

**Comment by servocoder** [comment] 2016-10-31 07:07
Glad to hear it works for you. You can face problems with DEV branch because of changes in the config files and other incompatible changes. It will be released as RichFilemenager v.2

**Closed by servocoder** 2016-10-31 07:07 UTC
