### ISSUE TITLE
Scrollbar issues

### ISSUE THREAD

**Issue by Iworb** [servocoder/RichFilemanager#98] opened 2017-02-03 07:25 UTC
Scrollbar doesn't initiate it some cases:

- When you upload many files into empty dir and files overflow container. I've uploaded 32 small files into your demo page (5 files per one upload). My display shows only files from 1 to 19 and scrollbar didn't appear.
- When you browsing through tree view main view updates depend on current tree view path and there's the same problem - scrollbar doesn't initiate. Check your demo page, try to click on 'Test_folder' (NB: your browser window should be not large enough to show all files. My resolution is 1280*1024).

**Comment by servocoder** [comment] 2017-02-03 07:51
1. That is true. After new files are added to the main view and overflow the container the vertical scrollbar should be recalculated, but it is not. Will be fixed.

2. I can't reproduce this one. Unlike the main view the vertical scrollbar in tree view works well and recalculates position on adding new files to the folder. Also the vertical scrollbar is appears correct when I open a folder with a lot of files, which overflow the container. If it wouldn't complicated for you, record a short video that demonstrates the problem, please.

**Comment by Iworb** [comment] 2017-02-03 07:56
I've upload video (Video_2017-02-03_105325.mp4) into your demo, because it's small enough :)
Like you can see, scrollbar on the main area wasn't appear when I select folder useing tree.

**Comment by servocoder** [comment] 2017-02-03 08:05
I see now. The scroll must be absent initially, before you open a folder with tons of files. That's the case :) Will be fixed too.

And what about vertical scrollbar in the tree view? Does it work nice for you just as for me?

**Comment by Iworb** [comment] 2017-02-03 08:18
Yup. There's no any problems with scrollbar there.
I also have some questions for you:
1. Is there a way to load files not all together, but partially? I have some folders with >2k files and it's really slow. Atm I'm trying to modify your RFM to add this functionality.
2. Is there way to add to main view files list without reloading view? I have some basic functionality to load files with ajax (100 per request when user scrolls more than 80% of content), but after that it completly reload view and drop scrollbar state. In the tree view everything is ok.
P.S. К слову, я говорю по-русски.

**Comment by servocoder** [comment] 2017-02-03 08:35
1. Nope, unfortunately, but I know about this problem. There was a request to add some kind of pagination. But I would prefer lazy loading feature while scrolling the page. What do you think? Actually I would glad if you can help with that. I have a lot of other thing in my todo list.

2. Hm, I see the problem. I have to take a look. Btw, it should be considered along with the lazy load / pagination feature. What if a newly uploaded file starts with letter "Z", and you are scrolled to "K"? Should we display this file after it's uploaded, as it done now? If so what happens when we scroll to the end? We should avoid files duplication.

P.S. Отлично, но тут лучше будем щеголять английским, чтобы другим тоже было понятно. На русском можем общаться по почте. Мой емайл есть в файле composer.json, например.

**Comment by Iworb** [comment] 2017-02-03 08:48
1. That is exactly what I'm looking for. I've done lazy loading (capturing scroll event and sending/receiving nodes by ajax) for tree view, but not for the main grid (because of reload view when loadList called).
2. There's easy to avoid files duplication: send files hash with files information and do not add duplicates into ItemObject array or just for upload case you could reload view completly or just don't add new files. One more solution is a new panel with 'last uploaded files'.

**Comment by servocoder** [comment] 2017-02-03 09:06
Ok, let me take a look on capability to add files without reloading the main view first.

**Closed** 2017-02-03 20:51 UTC
Labels: bug
