### ISSUE TITLE
How to extract .zip file using php connector

### ISSUE THREAD

**Issue by arvindkalbhor** [servocoder/RichFilemanager#146] opened 2017-04-04 10:28 UTC
Hey I want to extract my .zip folder using Rich Filemanager, help me for how to do this using php connector.

**Comment by servocoder** [comment] 2017-04-04 10:32
Duplicate of #22
There is no time line for this feature at the moment, however it's in todo list.
You can vote for #22. I close this one.

**Closed by servocoder** 2017-04-04 10:32 UTC
Labels: duplicate
