### ISSUE TITLE
codemirror.js missing from composer install 

### ISSUE THREAD

**Issue by julesverhaeren** [servocoder/RichFilemanager#301] opened 2018-03-16 23:44 UTC
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [x] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [ ] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---
For some reason filemanager/libs/CodeMirror/lib/codemirror.js is missing when I do a clean install with:

composer  create-project --prefer-dist servocoder/richfilemanager filemanager

This stops the filemanager from loading (causing an infinite spinner animation) but can be fixed by manually downloading a codemirror release and inserting the missing json. I've tried the composer install on two systems with the same result, which leads me to think that the problem might be with the composer package. (It should be reproducible by just doing a clean install, copying the example config and trying to open the demo page)

**Comment by servocoder** [comment] 2018-03-17 00:32
Thanks for reporting.
The issue was caused by the recent refactoring.
Bugfix released in the v2.7.4

**Closed by servocoder** 2018-03-17 00:32 UTC
