### ISSUE TITLE
S3 Plugin, defaultAcl doesn't seem to work

### ISSUE THREAD

**Issue by avatar** [servocoder/RichFilemanager#152] opened 2017-04-05 10:02 UTC
All the files uploaded to s3, seem to be private, even if i specify the defaultAcl to 'public-read'. 
Normally that should be enough to set the files public. Am I missing something else?

**Comment by servocoder** [comment] 2017-04-06 06:48
Can't say much on this subject at the moment. I have to check it.

**Comment by avatar** [comment] 2017-04-21 06:55
Do you have some update on this issue?  Thanks!

**Comment by servocoder** [comment] 2017-04-21 07:42
This seems not ralated to RFM. Please, check this topic http://stackoverflow.com/q/19176926/7095038, and let me know if you solve the problem.

**Comment by avatar** [comment] 2017-04-21 07:59
I tried it, and ideed it works. But, the specified ACL is still ignored by RFM. I removed the policy, and in the file S3UploadHandler.php i added the public-read ACL on line 189:

```
stream_context_create(array(
                        's3' => array(
                            // it's possible to define mime type only for the first chunk of a file, but each consecutive
                            // chunk that appended overrides object's ContentType to the S3 default "binary/octet-stream".
                            // The only solutions is to define mime type based on file extension
                            'ContentType' => mime_type_by_extension($name),
                            'ACL' => 'public-read'
                        )
                    ))
```
This also works, even without the bucket policy.

Anyway, it works, thank you very much for your time! I appreciate it.

**Comment by servocoder** [comment] 2017-04-21 08:05
Does specified ACL affect on uploaded file if you specify it in the stream context (as you depict at the code snippet)? If this solves the problem with ACL I will add it to one of further releases.

**Comment by avatar** [comment] 2017-04-21 08:17
Yes, files uploaded will have the correct ACL, even without a bucket policy.

**Comment by servocoder** [comment] 2017-04-21 08:23
Great! I will close this issue after release of your modification.
Thank you for the fix.

**Comment by servocoder** [comment] 2017-04-22 16:45
I have pushed fix to the master branch. Could you test the latest version and report if the problem is fixed?

**Comment by avatar** [comment] 2017-04-24 17:59
I'll try to test it tomorrow. One thing: i think you should also add the extra line in the ELSE part of the IF (line 197).
I'll report back tomorrow.

**Comment by avatar** [comment] 2017-04-25 07:28
Hi, I just tested it, and it works like expected.

**Comment by servocoder** [comment] 2017-04-25 07:30
Thanks for feedback

**Closed by servocoder** 2017-04-25 07:30 UTC
Labels: bug
